### PR TITLE
dump: Fixup for quad faces (length>3)

### PR DESCRIPTION
**Pull request by nigels-com**
The face callback in the dump utility seems to assume triangle faces.

This change generalises the handling for quads and other faces of length > 3.

### CODE REVIEW

**Comment by paulharris** [comment]
I had a go at editing the code via the web,
just fixing up the if() so it covers all of the cases.
There was a chance if (eg) index == -2, it would print out the index... which is different to the original switch behaviour.

**Comment by paulharris** [comment]
What do you think?

**Comment by nigels-com** [comment]
Ah, fair point.
I don't think value_index can be < -1 or >= length, but better to guard against those, agreed.

I think this check `value_index <= length` ought to be `value_index < length`.
(I think the callback value_indexes are [-1, 0, 1, 2] for a triangle and [-1, 0, 1, 2, 3] for a quad.)

**Comment by nigels-com** [comment]
Will test your version too, give me 24 hours for that.

**Comment by paulharris** [comment]
You can take as much time as you like, I'm not currently actively using librply, but I'm happy to accept merge requests so we dont have yet another fork on github :)

**Comment by nigels-com** [comment]
Understood.  Happy to have a second opinion and not maintain a fork!  :smile:

**Pull request merged**
