### PR TITLE
Support for UTF8 filenames on Windows

### PR DESCRIPTION
**Pull request by nigels-com**
This change adds support for rply to read and write files with Unicode names on Windows.

### CODE REVIEW

**Comment by nigels-com** [comment]
I need to do some testing on Windows, before it gets merged.

**Comment by paulharris** [comment]
I've converted to a draft while you test.
Windows filenames are tricky, you have to use the \\?\ path format if you want to handle very long filenames too.
(only supports absolute file paths)   But that file path format can be the job of the function caller.

**Comment by nigels-com** [comment]
Tested on Windows.  Good to go.

I was able to read `日本.ply` and write to ` 中国.ply`.

**Comment by paulharris** [comment]
Is it worth adding WIN32_LEAN_AND_MEAN ?
ie add ```#define WIN32_LEAN_AND_MEAN``` before #include <windows.h>

**Comment by nigels-com** [comment]
Yes, I think I tried that.  That also works.  Seemed like more "mess" to me.
Neutral on that.

**Comment by paulharris** [comment]
It cuts out a lot of the windows.h mess, I always add it when including windows.h otherwise there can be some unwelcome surprises.

**Comment by nigels-com** [comment]
Done.

**Comment by paulharris** [comment]
Thanks Nigel !

**Pull request merged**
